/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
import { IEvolutionDetail } from "pokeapi-typescript";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface PokemonDetails {
    }
    interface PokemonEvolutionChain {
    }
    interface PokemonEvolutionDetails {
        "evolutionDetails": IEvolutionDetail[];
    }
    interface PokemonSearch {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPokemonDetailsElement extends Components.PokemonDetails, HTMLStencilElement {
    }
    var HTMLPokemonDetailsElement: {
        prototype: HTMLPokemonDetailsElement;
        new (): HTMLPokemonDetailsElement;
    };
    interface HTMLPokemonEvolutionChainElement extends Components.PokemonEvolutionChain, HTMLStencilElement {
    }
    var HTMLPokemonEvolutionChainElement: {
        prototype: HTMLPokemonEvolutionChainElement;
        new (): HTMLPokemonEvolutionChainElement;
    };
    interface HTMLPokemonEvolutionDetailsElement extends Components.PokemonEvolutionDetails, HTMLStencilElement {
    }
    var HTMLPokemonEvolutionDetailsElement: {
        prototype: HTMLPokemonEvolutionDetailsElement;
        new (): HTMLPokemonEvolutionDetailsElement;
    };
    interface HTMLPokemonSearchElement extends Components.PokemonSearch, HTMLStencilElement {
    }
    var HTMLPokemonSearchElement: {
        prototype: HTMLPokemonSearchElement;
        new (): HTMLPokemonSearchElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "pokemon-details": HTMLPokemonDetailsElement;
        "pokemon-evolution-chain": HTMLPokemonEvolutionChainElement;
        "pokemon-evolution-details": HTMLPokemonEvolutionDetailsElement;
        "pokemon-search": HTMLPokemonSearchElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface PokemonDetails {
    }
    interface PokemonEvolutionChain {
    }
    interface PokemonEvolutionDetails {
        "evolutionDetails"?: IEvolutionDetail[];
    }
    interface PokemonSearch {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "pokemon-details": PokemonDetails;
        "pokemon-evolution-chain": PokemonEvolutionChain;
        "pokemon-evolution-details": PokemonEvolutionDetails;
        "pokemon-search": PokemonSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "pokemon-details": LocalJSX.PokemonDetails & JSXBase.HTMLAttributes<HTMLPokemonDetailsElement>;
            "pokemon-evolution-chain": LocalJSX.PokemonEvolutionChain & JSXBase.HTMLAttributes<HTMLPokemonEvolutionChainElement>;
            "pokemon-evolution-details": LocalJSX.PokemonEvolutionDetails & JSXBase.HTMLAttributes<HTMLPokemonEvolutionDetailsElement>;
            "pokemon-search": LocalJSX.PokemonSearch & JSXBase.HTMLAttributes<HTMLPokemonSearchElement>;
        }
    }
}
